import "@app/globals.css";
import type { Metadata } from "next";
import Navigation from "@/components/navigation/Navigation";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next styles",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full min-h-full">
        <div className="antialiased max-w-2xl flex flex-col mx-auto">
          <header className="flex flex-row items-center py-8">
            <section className="relative -top-0.5">
              <Link className="text-lg font-bold text-gray-900" href="/">
                cdgn.
              </Link>
            </section>
            <section className="ml-2">
              <Navigation />
            </section>
          </header>
          <main className="flex flex-col">{children}</main>
        </div>
      </body>
    </html>
  );
}
